### PR TITLE
Possible implementation of a matches method.

### PR DESCRIPTION
**Pull request by rripken**
I see that someone else also suggested an implementation of a matches or hasMatches method.  That the other branch didn't properly account for the TrieConfig options and didn't include test cases.   
Basic idea is that in some cases it isn't important to know what the match is, only whether or not a string contains a match.  In those cases the method can return as soon as it finds the first suitable match.  With a large number of search keywords and a large string to search the difference between finding the first match and finding all matches can be very significant.  

Maybe "contains" or "containsAny" would be a better method name.

### CODE REVIEW

**Comment by arcadius** [comment]
+1
This is exactly what I have been looking for.

**Comment by rripken** [comment]
I sort of gave up on this getting merged.  I liked this aho-corasick implementation because its was modern and clean and easily usable from Maven projects.  I see there are several forks and nothing gets merged back.  I started using https://hkn.eecs.berkeley.edu/~dyoo/java/index.html .  Even with my suggested containsAny method the dyoo implementation was still faster.  If you find that you need Aho-Corasick that usually means that you really need it and fastest impl wins...

**Comment by jeffrey-aguilera** [comment]
@rripken Thank for the link.  This projects does not seem to be actively maintained.  The code generates numerous NPEs, even when run on a single thread and only running parseText after the Trie is fully constructed.  Real world suitability is dubious.

**Comment by robert-bor** [comment]
Thanks for the pull request, changes implemented.

**Pull request closed without merging**
